name: Upload CV File

on:
  push:
    branches:
      - main

jobs:
  upload-cv:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Upload CV File
      uses: actions/upload-artifact@v2
      with:
        name: cv
        path: src/cv.tex
